### ISSUE TITLE
Error in debug

### ISSUE THREAD

**Issue by reob-info** [JetBrains/awesome-pycharm#15]
"C:\Program Files\Python39\python.exe" "C:\Program Files\JetBrains\PyCharm Community Edition 2020.3.5\plugins\python-ce\helpers\pydev\pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 51159 --file C:/dev/test/python/fastapi/code/test.py
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.3.5\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_console_integration.py", line 4, in <module>
    from code import InteractiveConsole
ImportError: cannot import name 'InteractiveConsole' from 'code' (C:\dev\test\python\fastapi\code\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.3.5\plugins\python-ce\helpers\pydev\pydevd.py", line 45, in <module>
    from _pydevd_bundle.pydevd_comm import CMD_SET_BREAK, CMD_SET_NEXT_STATEMENT, CMD_STEP_INTO, CMD_STEP_OVER, \
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.3.5\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_comm.py", line 91, in <module>
    from _pydevd_bundle import pydevd_console_integration
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.3.5\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevd_console_integration.py", line 6, in <module>
    from _pydevd_bundle.pydevconsole_code_for_ironpython import InteractiveConsole
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2020.3.5\plugins\python-ce\helpers\pydev\_pydevd_bundle\pydevconsole_code_for_ironpython.py", line 305
    exec code in self.locals
         ^
SyntaxError: Missing parentheses in call to 'exec'

I don't know why he is trying to import Interactive console from my `__init__.py`

**Comment by pauleveritt** [comment]
Hi, this repo is not a forum for PyCharm. Two suggestions: [Reddit](https://www.reddit.com/r/pycharm/) and our [support forum](https://intellij-support.jetbrains.com/hc/en-us/community/topics/200379535-PyCharm). If you want to report a bug or a feature, our [issue tracker](https://youtrack.jetbrains.com/issues?q=project%3A%20py) is the place.
